// <auto-generated />
namespace FaceYourNation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Take19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Take19));
        
        string IMigrationMetadata.Id
        {
            get { return "201606231623418_Take19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
